pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
      - python setup.py install
      - pip install -r dev-requirements.txt
      - make test

matrix:
  PYTHON_VERSION:
    - 3.7-stretch

branches: [ master, pci_*, ci_* ]
